### PR TITLE
Icon fix

### PR DESCRIPTION
**Pull request by RazerGhost**
icon's weren't working and glitched out standart qb-radialmenu. changed the icon name and now its fixed

### CODE REVIEW

**Comment by AnishBplayz** [comment]
update your radialmenu....

**Comment by RazerGhost** [comment]
> update your radialmenu....

It was updated to the latest.

**Comment by AnishBplayz** [comment]
nvm somehow i have the walking style on my side of radialmenu
image

But comparing with the updated radialmenu its gone... weirdd...

**Comment by RazerGhost** [comment]
that is weird yeah

**Comment by MonkeyWhisper** [comment]
Thank you! Merged in previous PR

**Pull request closed without merging**
